name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Setup GIT
        run: |
          git switch -c master
          git config --global user.email "argyle@google.com"
          git config --global user.name "Adam Argyle"

      - name: Install & Build
        run: |
          npm install
          npm run extension:release

      - name: Deploy
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: cdockenadnadldjbbgcallicgledbeoc
          zip: extension/build/visbug.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Commit
        run: |
          git push
          git push origin --tags
